version: "3"
services:
  db:
    image: mariadb
    container_name: mariadb_${PROJECT_NAME}
    restart: "no"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin
    container_name: phpmyadmin_${PROJECT_NAME}
    restart: "no"
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    env_file:
      - .env
    image: maildev/maildev
    container_name: maildev_${PROJECT_NAME}
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - ${MAILDEV_PORT}:80
    restart: "no"
    networks:
      - dev

  php:
    env_file:
      - .env
    build:
      context: docker/php
      args:
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER}
        - GROUP_NAME=${GROUP}
        - FOLDER=${SYMFONY_FOLDER_NAME}
    container_name: php_apache_${PROJECT_NAME}
    ports:
      - ${PHP_APACHE_PORT}:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: "no"
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
